//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRMIssues.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClassesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRMIssues.Resources.ClassesResources", typeof(ClassesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine &amp;Issues.
        /// </summary>
        internal static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem establishing a connection to check for updates:{0}.
        /// </summary>
        internal static string ErrorInUpdatesConnectionMessage {
            get {
                return ResourceManager.GetString("ErrorInUpdatesConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates.
        /// </summary>
        internal static string ErrorInUpdatesConnectionTitle {
            get {
                return ResourceManager.GetString("ErrorInUpdatesConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred retrieving the issue list:{0}.
        /// </summary>
        internal static string ErrorReadingIssuesListMessage {
            get {
                return ResourceManager.GetString("ErrorReadingIssuesListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read issue list.
        /// </summary>
        internal static string ErrorReadingIssuesListTitle {
            get {
                return ResourceManager.GetString("ErrorReadingIssuesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedUrl is not provided..
        /// </summary>
        internal static string FeedParser_FeedParser_feedUrl_is_not_provided {
            get {
                return ResourceManager.GetString("FeedParser_FeedParser_feedUrl_is_not_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string IssueText {
            get {
                return ResourceManager.GetString("IssueText", resourceCulture);
            }
        }
    }
}
