//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurtleMine.Resources
{


	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurtleMine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Word (Empty for a blank entry):.
        /// </summary>
        internal static string AddWord {
            get {
                return ResourceManager.GetString("AddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Word.
        /// </summary>
        internal static string AddWord_Title {
            get {
                return ResourceManager.GetString("AddWord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Download complete. {0} Issues displayed..
        /// </summary>
        internal static string AtomLoadComplete {
            get {
                return ResourceManager.GetString("AtomLoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Download failed.
        /// </summary>
        internal static string AtomLoadFailed {
            get {
                return ResourceManager.GetString("AtomLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Loading ATOM feed.
        /// </summary>
        internal static string AtomLoading {
            get {
                return ResourceManager.GetString("AtomLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine &amp;Issues.
        /// </summary>
        internal static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string ColumnAuthor {
            get {
                return ResourceManager.GetString("ColumnAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        internal static string ColumnLastUpdated {
            get {
                return ResourceManager.GetString("ColumnLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string ColumnNumber {
            get {
                return ResourceManager.GetString("ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string ColumnSummary {
            get {
                return ResourceManager.GetString("ColumnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurtleMine Configuration.
        /// </summary>
        internal static string Configuration_loadControls_Configuration_Utility {
            get {
                return ResourceManager.GetString("Configuration_loadControls_Configuration_Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurtleMine Configuration - Project Settings.
        /// </summary>
        internal static string Configuration_LoadControlsProject_Configuration_Utility___Project_Settings {
            get {
                return ResourceManager.GetString("Configuration_LoadControlsProject_Configuration_Utility___Project_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this item?.
        /// </summary>
        internal static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string Confirm_Delete_Title {
            get {
                return ResourceManager.GetString("Confirm_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to reset to default? All Changes will be lost!.
        /// </summary>
        internal static string Confirm_Reset {
            get {
                return ResourceManager.GetString("Confirm_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Reset.
        /// </summary>
        internal static string Confirm_Reset_Title {
            get {
                return ResourceManager.GetString("Confirm_Reset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string Connectivity_btnSSLPath_Click_All_Files {
            get {
                return ResourceManager.GetString("Connectivity_btnSSLPath_Click_All_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Files.
        /// </summary>
        internal static string Connectivity_btnSSLPath_Click_Certificate_Files {
            get {
                return ResourceManager.GetString("Connectivity_btnSSLPath_Click_Certificate_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Certificate File.
        /// </summary>
        internal static string Connectivity_btnSSLPath_Click_Select_Certificate_File {
            get {
                return ResourceManager.GetString("Connectivity_btnSSLPath_Click_Select_Certificate_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must keep at least one column!.
        /// </summary>
        internal static string ErrorColumnRequiredMessage {
            get {
                return ResourceManager.GetString("ErrorColumnRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Missing.
        /// </summary>
        internal static string ErrorColumnRequiredTitle {
            get {
                return ResourceManager.GetString("ErrorColumnRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to continue anyway?.
        /// </summary>
        internal static string ErrorConfirmContinue {
            get {
                return ResourceManager.GetString("ErrorConfirmContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem establishing a connection to check for updates:{0}.
        /// </summary>
        internal static string ErrorInUpdatesConnectionMessage {
            get {
                return ResourceManager.GetString("ErrorInUpdatesConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates.
        /// </summary>
        internal static string ErrorInUpdatesConnectionTitle {
            get {
                return ResourceManager.GetString("ErrorInUpdatesConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred retrieving the issue list:{0}.
        /// </summary>
        internal static string ErrorReadingIssuesListMessage {
            get {
                return ResourceManager.GetString("ErrorReadingIssuesListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read issue list.
        /// </summary>
        internal static string ErrorReadingIssuesListTitle {
            get {
                return ResourceManager.GetString("ErrorReadingIssuesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must keep at least one word in the list!.
        /// </summary>
        internal static string ErrorWordRequiredMessage {
            get {
                return ResourceManager.GetString("ErrorWordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Missing.
        /// </summary>
        internal static string ErrorWordRequiredTitle {
            get {
                return ResourceManager.GetString("ErrorWordRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedUrl is not provided. Please confirm the plugin settings in Tortoise..
        /// </summary>
        internal static string FeedParser_feedUrl_is_not_provided {
            get {
                return ResourceManager.GetString("FeedParser_feedUrl_is_not_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import / Export.
        /// </summary>
        internal static string ImportExport {
            get {
                return ResourceManager.GetString("ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string IssueText {
            get {
                return ResourceManager.GetString("IssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string OptionsDialog_btnTest_Click_Success {
            get {
                return ResourceManager.GetString("OptionsDialog_btnTest_Click_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully read atom feed: {0}.
        /// </summary>
        internal static string OptionsDialog_btnTest_Click_Successfully_read_atom_feed {
            get {
                return ResourceManager.GetString("OptionsDialog_btnTest_Click_Successfully_read_atom_feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string OptionsDialog_lnkFeedUrl_LinkClicked_Failed {
            get {
                return ResourceManager.GetString("OptionsDialog_lnkFeedUrl_LinkClicked_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open link!.
        /// </summary>
        internal static string OptionsDialog_lnkFeedUrl_LinkClicked_Unable_to_open_link {
            get {
                return ResourceManager.GetString("OptionsDialog_lnkFeedUrl_LinkClicked_Unable_to_open_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Repository Location.
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_Select_Repository_Location {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_Select_Repository_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory can not be identified as a know repository folder for Subversion, Git or Mecurial..
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_1 {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to continue anyway?.
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_2 {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_This_directory_can_not_be_identified_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Repository Type.
        /// </summary>
        internal static string ProjectDetails_btnRepoPath_Click_Unknown_Repository_Type {
            get {
                return ResourceManager.GetString("ProjectDetails_btnRepoPath_Click_Unknown_Repository_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine &amp;Issues.
        /// </summary>
        internal static string Redmine {
            get {
                return ResourceManager.GetString("Redmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refs.
        /// </summary>
        internal static string RefsText {
            get {
                return ResourceManager.GetString("RefsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchBoxNoResults {
            get {
                return ResourceManager.GetString("SearchBoxNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search : {0} occurrence(s).
        /// </summary>
        internal static string SearchBoxWithResults {
            get {
                return ResourceManager.GetString("SearchBoxWithResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fields.
        /// </summary>
        internal static string SearchFieldAllFields {
            get {
                return ResourceManager.GetString("SearchFieldAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;how.
        /// </summary>
        internal static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
    }
}
